return {
  "nvim-treesitter/nvim-treesitter",
  version = "*",
  build = ":TSUpdate",
  config = function()
    local configs = require('nvim-treesitter.configs')
    configs.setup {
      highlight = {
        enable = true,
      },
      indent = {
        enable = true
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = false,
          scope_incremental = false,
          node_incremental = "<TAB>",
          node_decremental = "<S-TAB>",
        },
      },
      auto_install = true,
      ignore_install = {},
      sync_install = false,
      ensure_installed = {
        'arduino',
        'bash',
        'bibtex',
        'c',
        'cpp',
        'css',
        'cmake',
        'diff',
        'gitignore',
        'gitattributes',
        'gitcommit',
        'git_config',
        'git_rebase',
        'html',
        'javascript',
        'json',
        'json5',
        'julia',
        'latex',
        'lua',
        'luadoc',
        'make',
        'markdown_inline',
        'matlab',
        -- 'PyPA manifest',
        -- 'pip requirements',
        'python',
        'r',
        'regex',
        'rst',
        'rust',
        'toml',
        'typescript',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
      },
    }
  end,
  cmd = {
    "TSInstall",
    "TSUninstall",
    "TSUpdate",
    "TSUpdateSync",
    "TSInstallInfo",
    "TSInstallSync",
    "TSInstallFromGrammar",
  },
  event = "User FileOpened",
}
