
-- Text objects
-- require("nvim-treesitter.configs").setup({
-- 	textobjects = {
-- 		select = {
-- 			enable = true,
-- 			keymaps = {
-- 				["ae"] = { query = "@block.outer", desc = "an environment" },
-- 				["ie"] = { query = "@block.inner", desc = "inside environment" },
-- 				["ac"] = { query = "@call.outer", desc = "a command" },
-- 				["ic"] = { query = "@call.inner", desc = "inside command" },
-- 			},
-- 		},
-- 	},
-- })
